#!/bin/bash 

mkdir DBs   # To create directory in the first time .. in the second time it will generate an error but it will disapear because (clear) in raw NO. 5!
cd DBs
clear

function Create_DB
{ 
    ReadDBNameFromUSer
    if test -d $DBname
    then
       echo -e "$DBname already exists!\n"
    else
        mkdir $DBname
        echo -e "Database $DBname has been created successfully :)\n"
    fi

    MainDB
}

function Open_DB
{
    ReadDBNameFromUSer  
    if test -d $DBname
    then
        cd $DBname
        pwd
        echo "Done."
        MainTables
    else
        echo -e "$DBname doesn't exist!\n"
    fi

    MainDB
}

function Drop_DB
{
    ReadDBNameFromUSer
    if [ -d $DBname ]
    then 
        echo "Are you sure? y|n "
        read choice
        if [ $choice = "y" ]
        then
            rm -r $DBname
            echo -e "Database $DBname has been removed successfully :)\n\n"
        else
            MainDB
        fi
    else
        echo -e "$DBname doesn't exist!\n\n"
    fi  

    MainDB       
}

function list_DBs
{
    if [ "$(ls -A)" ]
    then
        echo -e "Available Database/s: ";ls
        echo -e "\n"  
    else
        echo "No Databases to show!"
    fi

    MainDB 
}

function ReadDBNameFromUSer
{
    echo -e "Enter Database name: \c"
	read DBname    
}

function MainDB
{  
    select choice in 'Create Database' 'Open Database' 'Drop Database' 'List Database' 'Exit'
    do 
        case $REPLY in 
            1 ) Create_DB
            ;;
            2 ) Open_DB 
            ;;
            3 ) Drop_DB
            ;;
            4 ) list_DBs 
            ;;
            5 ) clear; exit 0
            ;;
            * ) echo -e "Invalid Input :(\n" ; MainDB
        esac
        
    done
}

function List_All_Tables
{
    ls ; MainTables
}

function Open_Certain_table
{
    ReadTableNameFromUSer
    if [ -f $Tablename ]
    then
        cat $Tablename
       ####   Here we gonna Call the Record stage   ####
    else
        echo -e "$Tablename doesn't exist!\n"
    fi

    MainTables
}

function Create_table
{
    ReadTableNameFromUSer
    if [ -f $Tablename ]
    then
        echo -e "$Tablename already exist!\n"
    else
        echo -e "Number of Columns: \c"
        read columnsNumber
        seperator="|"
        raw_seperator="\n"
        pKey=""
        counter=1
        metaData="Column Name"$seperator"Type"$seperator"Primary Key"
        while [ $counter -le $columnsNumber ]
        do
            echo -e "Name of Column Number ($counter): \c"
            read columnName

            echo -e "Type of Column $columnName: "
            select type in "integer" "string"
            do
                case $type in
                    integer ) columnType="integer";
                    break
                    ;;
                    string ) columnType="string";
                    break
                    ;;
                    * ) echo "Invalid Input :(" 
                    ;;
                esac
            done

            if [[ $pKey == "" ]]; 
            then
                echo -e "Make Primary Key ?"
                select var in "yes" "no"
                do
                    case $var in
                        yes ) pKey="PK"; metaData+=$raw_seperator$columnName$seperator$columnType$seperator$pKey;
                        break
                        ;;
                        no ) metaData+=$raw_seperator$columnName$seperator$columnType$seperator"";
                        break
                        ;;
                        * ) echo "Invalid Input :(" 
                        ;;
                    esac
                done
            else
                metaData+=$raw_seperator$columnName$seperator$columnType$seperator""
            fi

            if [[ $counter == $columnsNumber ]]; 
            then
                data=$data$columnName
            else
                data=$data$columnName$seperator
            fi

            ((counter++))

        done
        
        touch .$Tablename
        echo -e $metaData >> .$Tablename
        touch $Tablename
        echo -e $data >> $Tablename

        if [[ $? == 0 ]]
        then
            echo -e "Table Created Successfully :)\n"
        else
            echo -e "NOT Successful Creation of Table $Tablename :(\n"
        fi
    fi

    MainTables
}

function Drop_table
{
    ReadTableNameFromUSer
    if [ -f $Tablename ]
    then 
        echo "Are you sure? y|n "
        read choice
        if [ $choice = "y" ]
        then
            rm $Tablename .$Tablename
            echo -e "$Tablename Table has been removed successfully :)\n\n"
        else
            clear; MainTables
        fi
    else
        echo -e "$Tablename Table doesn't exist!\n\n"
    fi  

    MainTables
}

function ReadTableNameFromUSer
{
    echo -e "Enter Table name: \c"
	read Tablename
}

function MainTables
{
    select choice in 'List All Tables' 'Open Certain Table' 'Create Table' 'Drop Table' 'Back to DB Menu' 'Exit'
    do
        case $REPLY in 
            1 ) List_All_Tables 
            ;;
            2 ) Open_Certain_table 
            ;;
            3 ) Create_table 
            ;; 
            4 ) Drop_table
            ;;
            5 ) clear; cd ../; MainDB
            ;;
            6 ) clear; exit 0
            ;;
            * ) echo -e "Invalid Input :(\n" ; MainTables  
        esac
        
    done
}

MainDB
